import { Request } from 'express';

import { env } from '@/config/env';
import { ApiError } from '@/error/ApiError';

/**
 * Builds the response body for a failed request.
 *
 * The shape is identical for every error in the application. Clients can write
 * one error handler instead of one per endpoint, and `errorId` lets support
 * match a user's screenshot to a line in the logs.
 *
 * @param errorId - generated by the error handler and written to the logs too
 */
export interface ApiErrorResponse {
    success: false;
    status: 'error';
    statusCode: number;
    error: {
        errorId: string;
        requestId: string | undefined;
        name: string;
        code: string;
        message: string;
        details: string;
        suggestion: string;
        ip: string | null | undefined;
        url: string;
        method: string;
        timestamp: string;
        stack: string | undefined;
    };
}

export const apiErrorFormat = (req: Request, error: ApiError, errorId: string): ApiErrorResponse => {
    const isDevelopment = env.app.NODE_ENV === 'development';

    return {
        success: false,
        status: 'error',
        statusCode: error.statusCode,
        error: {
            errorId,
            requestId: req.rid,
            name: error.name,

            code: error.errorCode,
            message: error.message,
            details: error.details,
            suggestion: error.suggestion,

            ip: req.clientIp,
            /**
             * @note `"ip": "::ffff:192.168.18.165"` is not a bug. Node reports
             * IPv4 addresses as IPv4-mapped IPv6 addresses on dual-stack
             * sockets.
             * @link https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses
             */

            url: req.originalUrl,
            method: req.method,

            timestamp: error.timestamp.toISOString(),

            /**
             * Stack traces reveal file paths, dependency versions and internal
             * logic. They are useful locally and a gift to an attacker in
             * production, so they never leave the server outside development.
             */
            stack: isDevelopment ? error.stack : undefined,
        },
    };
};
